# Generated by Django 3.2.7 on 2022-01-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=30)),
            ],
        ),
    ]
